POST http://localhost:8000/api/post/
Host: localhost:8000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzMzOTIxMjE4LCJpYXQiOjE3MzM5MjAzMTgsImp0aSI6ImFhY2RmMzJmZjVjNTRmZWY5NzJlNGEyNjNmZmZmZjY2IiwidXNlcl9pZCI6MX0.0dqPICp61VoLfMQR_RCPIvEn8GZcG5Mb69Oe-pEWZM8
Content-Type: application/json

{
  "title": "My New Post",
  "content": "This is the content of my new post."
}
